/**
 * @file ns_ca_bundle.h
 * @brief The embedded trust store: the Mozilla roots, one copy for all.
 *
 * The array lives in ns_ca_bundle.c, which is GENERATED by
 * tools/make_ca_bundle.py from lib/ca-bundle/cacert.pem and committed;
 * check_release.py regenerates and diffs it, so the array and the PEM
 * cannot disagree.  One bundle everywhere is decision 3 of
 * design/work-items/tls-rollout.md: the NDK has no system trust store,
 * and every product must give the same answer about the same caster.
 *
 * Project: NTRIP-Analyser
 * Author: Remko Welling, PE1MEW
 * License: Apache License 2.0 with Commons Clause
 */
#ifndef NS_CA_BUNDLE_H
#define NS_CA_BUNDLE_H

#ifdef __cplusplus
extern "C" {
#endif

/** The PEM text, NUL-terminated; the length includes the NUL, which is
 *  how mbedTLS wants a PEM buffer measured. */
extern const unsigned char ns_ca_bundle_pem[];
extern const unsigned int  ns_ca_bundle_pem_len;

/** Mozilla's own date line, for the release check's age warning. */
extern const char ns_ca_bundle_date[];

#ifdef __cplusplus
}
#endif

#endif /* NS_CA_BUNDLE_H */
